#!/bin/bash

./build.pl $1 $2 $3

xhost +local:*

docker run \
    --device=/dev/kvm:/dev/kvm \
    --device=/dev/net/tun:/dev/net/tun \
    -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
    -e DISPLAY=${DISPLAY} \
    --rm \
    -it \
    `cat /tmp/current_img`
