import {
    AboutSlint,
    HorizontalBox,
    VerticalBox
} from "std-widgets.slint";

component TestNativeComponent {

}

component TextRow {
    in property <string> name;
    in property <string> value;

    in property <bool> top-separator: false;
    in property <bool> bottom-separator: true;

    VerticalBox {
        spacing: 0px;
        padding: 0px;
        if root.top-separator : Rectangle {
            height: 1px;
            background: #cecace;
        }
        HorizontalBox {
            spacing: 0px;
            Text {
                text: root.name;
                horizontal-alignment: left;
            }
            Text {
                text: root.value;
                color: #888888;
                horizontal-alignment: left;
            }
        }
        if root.bottom-separator : Rectangle {
            height: 1px;
            background: #cecace;
        }
    }
}

export component Demo inherits Window {
    in property <float> miliseconds;
    in property <float> tick;

    default-font-size: 22px;
    default-font-family: "Noto Sans";

    Rectangle {
        padding-left: 100px;
        border-color: #8800ff;
        border-width: 2px;
        background: #29bba7;
    }

    VerticalLayout {
        Rectangle {
            padding-left: 100px;
            border-color: #8800ff;
            border-width: 2px;
            background: #ffbba7;
            Image {
                padding-bottom: 20px;
                source: @image-url("assets/img/bananas.svg");
                height: 80px;
            }

        }

        //alignment: stretch;
        Text {
            text: "AA";//"Ticks: \{root.tick}";
            color: #ffffff;
        }
    }

    TestNativeComponent {

    }

    //TODO
    //VerticalLayout {
    //    padding: 2px;
    //    Image {
    //        padding-bottom: 20px;
    //        source: @image-url("/home/borys/projects/cpp/Bananas.svg");
    //        height: 80px;
    //    }
    //    TextRow {
    //        name: "Time:";
    //        value: root.miliseconds;
    //        top-separator: true;
    //    }
    //    TextRow {
    //        name: "Ticks:";
    //        value: root.tick;
    //    }
    //}
}
