#!/bin/bash

if [ ! -f "$1" ]; then
    >&2 echo "$1 does not exist."
    exit 1
fi

grub-file --is-x86-multiboot $1
echo "multiboot: $? (0 -> true)"
grub-file --is-x86-multiboot2 $1
echo "multiboot2: $? (0 -> true)"

if grub-file --is-x86-multiboot $1; then
    echo "multiboot confirmed"
elif grub-file --is-x86-multiboot2 $1; then
    echo "multiboot confirmed (multiboot2)"
else
    >&2 echo "the file $1 is not multiboot"
    exit 2
fi

binname="$(basename -- $1)" 
bindir="$(dirname -- $1)" 

mkdir -p $bindir/isodir/boot/grub
cp $1 $bindir/isodir/boot/$binname
cp $2 $bindir/isodir/boot/grub/grub.cfg
grub-mkrescue -o $bindir/kernel.iso $bindir/isodir