#!/bin/bash

# first arg  - path to binary
# second arg - path to grub cfg

GREEN_CODE="32"
GREEN="\e[${GREEN_CODE}m"
BOLDGREEN="\e[1;${GREEN_CODE}m"
ENDCOLOR="\e[0m"

if [ -z "$1" ]; then
    >&2 echo "$0: error: first argument missing"
    exit 1
fi

if [ -z "$2" ]; then
    >&2 echo "$0: error: second argument missing"
    exit 1
fi

if [ ! -f "$1" ]; then
    >&2 echo "$0: error: $1 does not exist."
    exit 1
fi

if grub-file --is-x86-multiboot $1; then
    echo -e "${BOLDGREEN}Multiboot confirmed${ENDCOLOR}"
elif grub-file --is-x86-multiboot2 $1; then
    echo -e "${BOLDGREEN}Multiboot confirmed (multiboot2)${ENDCOLOR}"
else
    >&2 echo "$0: error: the file $1 is not multiboot"
    exit 2
fi

binname="$(basename -- $1)"
bindir="$(dirname -- $1)"

mkdir -p $bindir/isodir/boot/grub
cp $1 $bindir/isodir/boot/$binname
cp $2 $bindir/isodir/boot/grub/grub.cfg
grub-mkrescue -o $bindir/kernel.iso $bindir/isodir
